# Generated by Django 2.1.5 on 2019-01-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='style',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
